### ISSUE TITLE
Parse error inside SignalRGB console

### ISSUE THREAD

**Issue by Alx941126** [Fefedu973/SignalRGB-To-OpenRGB-Bridge#1]
Good day. 

I've followed the instructions as written, however there is the next issue:

[17:48:41]: Loading Interface...
[17:48:41]: Loading Interface via .qml file...
[17:48:41]: Interface Loaded!
[17:48:41]: qrc:/Qml/Device/Editors/OpenRGB Bridge:13: SyntaxError: JSON.parse: Parse error

I don't know if it's an issue on your code, but it's happening since the first time. I've tried deleting the plugin and reinstalling it, same with OpenRGB.

**Comment by Alx941126** [comment]
nvm found it. line 13, replace ] with }.

**Comment by Alx941126** [comment]
error found and submitted.

**Comment by Fefedu973** [comment]
I cannot find the issue line 13. In which file ?

**Comment by Fefedu973** [comment]
More peoples have this issue, i cannot find the issue you mentionned I need to investigate

**Comment by Fefedu973** [comment]
A quick fix is to click on the "DELETE ALL" button (it reset the plugin and it solved the issue for some peoples) maybe the issue is that when i make the plugin the values are being created to the registry but when it is the first time launching it there is a bug that prevent to work as expected

**Comment by Fefedu973** [comment]
I fixed the json parse error by adding error check and handling
