### ISSUE TITLE
Keyboard gets laggy if it's enabled in SignalRGB

### ISSUE THREAD

**Issue by 5hp1k** [Fefedu973/SignalRGB-To-OpenRGB-Bridge#8]
If you select a keyboard in SignalRGB while the plugin server's online, all the RGB effects will work just fine, but the keyboard itself will get extremely buggy: the pressed key won't stop being printing a pressed symbol until you press another key and so on.

**Comment by 5hp1k** [comment]
![image](https://github.com/Fefedu973/SignalRGB-To-OpenRGB-Bridge/assets/33803303/2653a65c-2446-4746-ad71-e3bacc2ed612)
To demonstrate the issue, this is my attemt of printing "hello world"

**Comment by Fefedu973** [comment]
# I don't understand, when does this happen?

**Comment by 5hp1k** [comment]
After some research, I've found out that the image is absolutely unrelated to your plugin.
![image](https://github.com/Fefedu973/SignalRGB-To-OpenRGB-Bridge/assets/33803303/f3b1f800-1261-4828-80de-6fbff3170d6c)
As can be seen on the screenshot, the issue is linked to my keyboard.
Sorry for disturbance xD
